name: todo_torsten
description: "Tordy - A simple todo app for your daily tasks."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/mainbg.png
    - assets/images/todocardbg.png
